import { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  // --- T-SHIRTS ---
  {
    id: 1,
    external_id: 'MYN-TSH-001',
    retailer: 'Myntra',
    brand: 'Roadster',
    name: 'Men Black Solid Oversized T-Shirt',
    description: 'Pure cotton heavy drop-shoulder oversized t-shirt with classic crew neck.',
    category: 'T-shirts',
    subcategory: 'Oversized',
    gender: 'Men',
    price: 799,
    currency: 'INR',
    discount: 35,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.myntra.com/tshirts/roadster/men-black-oversized/1001',
    affiliate_url: 'https://myntra.com/aff/aimirror/1001',
    available_sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black'],
    fit_type: 'Oversized',
    material: '100% Cotton',
    rating: 4.6,
    size_charts: [
      { id: 101, size_label: 'S', chest_min: 92, chest_max: 96, shoulder_min: 44, shoulder_max: 46, waist_min: 78, waist_max: 82, length_cm: 70 },
      { id: 102, size_label: 'M', chest_min: 98, chest_max: 103, shoulder_min: 46.5, shoulder_max: 48.5, waist_min: 84, waist_max: 88, length_cm: 72 },
      { id: 103, size_label: 'L', chest_min: 104, chest_max: 109, shoulder_min: 49, shoulder_max: 51, waist_min: 90, waist_max: 94, length_cm: 74 },
      { id: 104, size_label: 'XL', chest_min: 110, chest_max: 116, shoulder_min: 51.5, shoulder_max: 53.5, waist_min: 96, waist_max: 102, length_cm: 76 },
    ],
  },
  {
    id: 2,
    external_id: 'ZAR-TSH-002',
    retailer: 'Zara',
    brand: 'Zara',
    name: 'Heavyweight Textured White Tee',
    description: 'Minimalist premium cotton white tee featuring structured silhouette.',
    category: 'T-shirts',
    subcategory: 'Crew Neck',
    gender: 'Unisex',
    price: 1490,
    currency: 'INR',
    discount: 10,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.zara.com/in/en/heavyweight-textured-white-tee-p1002',
    affiliate_url: 'https://zara.com/aff/aimirror/1002',
    available_sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White'],
    fit_type: 'Regular Fit',
    material: '100% Organic Cotton',
    rating: 4.8,
    size_charts: [
      { id: 201, size_label: 'S', chest_min: 92, chest_max: 96, shoulder_min: 44, shoulder_max: 45.5, waist_min: 78, waist_max: 82, length_cm: 69 },
      { id: 202, size_label: 'M', chest_min: 98, chest_max: 102, shoulder_min: 46, shoulder_max: 47.5, waist_min: 84, waist_max: 88, length_cm: 71 },
      { id: 203, size_label: 'L', chest_min: 104, chest_max: 108, shoulder_min: 48, shoulder_max: 49.5, waist_min: 90, waist_max: 94, length_cm: 73 },
    ],
  },
  {
    id: 3,
    external_id: 'HM-TSH-003',
    retailer: 'H&M',
    brand: 'H&M',
    name: 'Graphic Sage Green Vintage Tee',
    description: 'Washed jersey fabric with subtle chest artwork and relaxed shoulders.',
    category: 'T-shirts',
    subcategory: 'Graphic',
    gender: 'Men',
    price: 999,
    currency: 'INR',
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www2.hm.com/en_in/productpage.1003.html',
    affiliate_url: 'https://hm.com/aff/aimirror/1003',
    available_sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sage Green'],
    fit_type: 'Relaxed Fit',
    material: '100% Cotton',
    rating: 4.4,
    size_charts: [
      { id: 301, size_label: 'S', chest_min: 90, chest_max: 95, shoulder_min: 43, shoulder_max: 45, waist_min: 76, waist_max: 80, length_cm: 68 },
      { id: 302, size_label: 'M', chest_min: 96, chest_max: 101, shoulder_min: 45.5, shoulder_max: 47.5, waist_min: 82, waist_max: 86, length_cm: 70 },
      { id: 303, size_label: 'L', chest_min: 102, chest_max: 107, shoulder_min: 48, shoulder_max: 50, waist_min: 88, waist_max: 93, length_cm: 72 },
    ],
  },

  // --- SHIRTS ---
  {
    id: 4,
    external_id: 'AJI-SHI-004',
    retailer: 'AJIO',
    brand: 'Netplay',
    name: 'Men Slim Fit Linen Casual Shirt',
    description: 'Breathable pure linen button-down shirt ideal for summer layering.',
    category: 'Shirts',
    subcategory: 'Casual Shirts',
    gender: 'Men',
    price: 1299,
    currency: 'INR',
    discount: 40,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.ajio.com/netplay-linen-casual-shirt/p/1004',
    affiliate_url: 'https://ajio.com/aff/aimirror/1004',
    available_sizes: ['38', '40', '42', '44'],
    colors: ['Sky Blue', 'White'],
    fit_type: 'Slim Fit',
    material: '100% Linen',
    rating: 4.5,
    size_charts: [
      { id: 401, size_label: '38', chest_min: 94, chest_max: 98, shoulder_min: 43, shoulder_max: 44.5, waist_min: 80, waist_max: 84, length_cm: 73 },
      { id: 402, size_label: '40', chest_min: 99, chest_max: 103, shoulder_min: 45, shoulder_max: 46.5, waist_min: 85, waist_max: 89, length_cm: 75 },
      { id: 403, size_label: '42', chest_min: 104, chest_max: 108, shoulder_min: 47, shoulder_max: 48.5, waist_min: 90, waist_max: 94, length_cm: 77 },
    ],
  },
  {
    id: 5,
    external_id: 'AMZ-SHI-005',
    retailer: 'Amazon',
    brand: 'Symbol Premium',
    name: 'Classic White Formal Cotton Shirt',
    description: 'Wrinkle-resistant twill weave formal dress shirt with stiff collar.',
    category: 'Shirts',
    subcategory: 'Formal Shirts',
    gender: 'Men',
    price: 1099,
    currency: 'INR',
    discount: 15,
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.amazon.in/dp/B005AMZ1005',
    affiliate_url: 'https://amazon.in/aff/aimirror/1005',
    available_sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White'],
    fit_type: 'Regular Fit',
    material: '100% Egyptian Cotton',
    rating: 4.3,
    size_charts: [
      { id: 501, size_label: 'M', chest_min: 98, chest_max: 102, shoulder_min: 45.5, shoulder_max: 47, waist_min: 84, waist_max: 88, length_cm: 76 },
      { id: 502, size_label: 'L', chest_min: 104, chest_max: 108, shoulder_min: 47.5, shoulder_max: 49, waist_min: 90, waist_max: 95, length_cm: 78 },
    ],
  },

  // --- JACKETS ---
  {
    id: 6,
    external_id: 'MYN-JKT-006',
    retailer: 'Myntra',
    brand: 'Levis',
    name: 'Men Trucker Denim Jacket',
    description: 'Authentic indigo washed denim trucker jacket with button closures.',
    category: 'Jackets',
    subcategory: 'Denim',
    gender: 'Men',
    price: 3499,
    currency: 'INR',
    discount: 30,
    images: [
      'https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.myntra.com/jackets/levis/trucker-denim/1006',
    affiliate_url: 'https://myntra.com/aff/aimirror/1006',
    available_sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Indigo Blue'],
    fit_type: 'Regular Fit',
    material: '99% Cotton, 1% Elastane',
    rating: 4.9,
    size_charts: [
      { id: 601, size_label: 'M', chest_min: 100, chest_max: 105, shoulder_min: 46.5, shoulder_max: 48.5, waist_min: 86, waist_max: 91, length_cm: 66 },
      { id: 602, size_label: 'L', chest_min: 106, chest_max: 111, shoulder_min: 49, shoulder_max: 51, waist_min: 92, waist_max: 97, length_cm: 68 },
    ],
  },
  {
    id: 7,
    external_id: 'ZAR-JKT-007',
    retailer: 'Zara',
    brand: 'Zara',
    name: 'Matte Faux Leather Biker Jacket',
    description: 'Sleek black biker jacket with asymmetric zip and metallic hardware.',
    category: 'Jackets',
    subcategory: 'Leather',
    gender: 'Men',
    price: 4990,
    currency: 'INR',
    discount: 0,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.zara.com/in/en/biker-jacket-p1007',
    affiliate_url: 'https://zara.com/aff/aimirror/1007',
    available_sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black'],
    fit_type: 'Slim Fit',
    material: 'Polyurethane Faux Leather',
    rating: 4.7,
    size_charts: [
      { id: 701, size_label: 'M', chest_min: 98, chest_max: 102, shoulder_min: 45, shoulder_max: 46.5, waist_min: 84, waist_max: 88, length_cm: 65 },
      { id: 702, size_label: 'L', chest_min: 104, chest_max: 108, shoulder_min: 47, shoulder_max: 48.5, waist_min: 90, waist_max: 94, length_cm: 67 },
    ],
  },

  // --- DRESSES ---
  {
    id: 8,
    external_id: 'NYK-DRS-008',
    retailer: 'Nykaa',
    brand: 'Twenty Dresses',
    name: 'Women Floral Print Midi A-Line Dress',
    description: 'Charming floral printed midi dress with puff sleeves and cinched waist.',
    category: 'Dresses',
    subcategory: 'Midi',
    gender: 'Women',
    price: 1895,
    currency: 'INR',
    discount: 25,
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.nykaafashion.com/twenty-dresses-floral-midi/p/1008',
    affiliate_url: 'https://nykaafashion.com/aff/aimirror/1008',
    available_sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Multicolor Floral'],
    fit_type: 'Regular Fit',
    material: 'Viscose Rayon',
    rating: 4.7,
    size_charts: [
      { id: 801, size_label: 'S', chest_min: 85, chest_max: 89, shoulder_min: 37, shoulder_max: 38, waist_min: 69, waist_max: 73, length_cm: 112 },
      { id: 802, size_label: 'M', chest_min: 90, chest_max: 94, shoulder_min: 38.5, shoulder_max: 39.5, waist_min: 74, waist_max: 78, length_cm: 114 },
    ],
  },
  {
    id: 9,
    external_id: 'HM-DRS-009',
    retailer: 'H&M',
    brand: 'H&M',
    name: 'Little Black Ribbed Bodycon Dress',
    description: 'Stretchy ribbed jersey bodycon dress with square neck silhouette.',
    category: 'Dresses',
    subcategory: 'Bodycon',
    gender: 'Women',
    price: 1299,
    currency: 'INR',
    discount: 10,
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www2.hm.com/en_in/productpage.1009.html',
    affiliate_url: 'https://hm.com/aff/aimirror/1009',
    available_sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black'],
    fit_type: 'Slim Fit',
    material: '95% Cotton, 5% Elastane',
    rating: 4.5,
    size_charts: [
      { id: 901, size_label: 'S', chest_min: 83, chest_max: 87, shoulder_min: 36, shoulder_max: 37, waist_min: 65, waist_max: 69, length_cm: 90 },
      { id: 902, size_label: 'M', chest_min: 88, chest_max: 92, shoulder_min: 37.5, shoulder_max: 38.5, waist_min: 70, waist_max: 74, length_cm: 92 },
    ],
  },

  // --- JEANS & TROUSERS ---
  {
    id: 10,
    external_id: 'MYN-JNS-010',
    retailer: 'Myntra',
    brand: 'Levis',
    name: 'Men 511 Slim Fit Blue Jeans',
    description: 'Classic mid-rise dark indigo washed slim stretch denim.',
    category: 'Jeans',
    subcategory: 'Slim Fit',
    gender: 'Men',
    price: 2899,
    currency: 'INR',
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.myntra.com/jeans/levis/511-slim-blue/1010',
    affiliate_url: 'https://myntra.com/aff/aimirror/1010',
    available_sizes: ['30', '32', '34', '36'],
    colors: ['Dark Blue'],
    fit_type: 'Slim Fit',
    material: '98% Cotton, 2% Elastane',
    rating: 4.8,
    size_charts: [
      { id: 1001, size_label: '32', waist_min: 80, waist_max: 83, length_cm: 104 },
      { id: 1002, size_label: '34', waist_min: 85, waist_max: 88, length_cm: 106 },
    ],
  },
  {
    id: 11,
    external_id: 'ZAR-TRS-011',
    retailer: 'Zara',
    brand: 'Zara',
    name: 'Pleated Beige Relaxed Chino Trousers',
    description: 'Tailored double-pleated relaxed chino trousers with tapered leg.',
    category: 'Trousers',
    subcategory: 'Chinos',
    gender: 'Men',
    price: 2990,
    currency: 'INR',
    discount: 0,
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.zara.com/in/en/pleated-chino-p1011',
    affiliate_url: 'https://zara.com/aff/aimirror/1011',
    available_sizes: ['30', '32', '34', '36'],
    colors: ['Beige'],
    fit_type: 'Relaxed Fit',
    material: '100% Cotton Twill',
    rating: 4.6,
    size_charts: [
      { id: 1101, size_label: '32', waist_min: 81, waist_max: 84, length_cm: 103 },
      { id: 1102, size_label: '34', waist_min: 86, waist_max: 89, length_cm: 105 },
    ],
  },

  // --- SHOES ---
  {
    id: 12,
    external_id: 'AMZ-SHS-012',
    retailer: 'Amazon',
    brand: 'Nike',
    name: 'Court Vision Low Leather Sneakers',
    description: 'Retro basketball-inspired white low-top leather sneakers.',
    category: 'Shoes',
    subcategory: 'Sneakers',
    gender: 'Unisex',
    price: 5495,
    currency: 'INR',
    discount: 15,
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop',
    ],
    product_url: 'https://www.amazon.in/dp/B005AMZ1012',
    affiliate_url: 'https://amazon.in/aff/aimirror/1012',
    available_sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10'],
    colors: ['Triple White'],
    fit_type: 'Regular Fit',
    material: 'Real & Synthetic Leather',
    rating: 4.9,
    size_charts: [
      { id: 1201, size_label: 'UK 8', length_cm: 27.0 },
      { id: 1202, size_label: 'UK 9', length_cm: 28.0 },
    ],
  },
];

// Generate synthetic additional products to ensure all retailer & category filters have products
const BRANDS = ['Roadster', 'HRX', 'Levis', 'Zara', 'H&M', 'Mango', 'Twenty Dresses', 'Netplay', 'Puma', 'Nike', 'Adidas'];
const RETAILERS = ['Myntra', 'Nykaa', 'AJIO', 'Amazon', 'Zara', 'H&M'];
const CATEGORIES = ['T-shirts', 'Shirts', 'Jackets', 'Dresses', 'Jeans', 'Trousers', 'Shoes'];
const FITS = ['Regular Fit', 'Slim Fit', 'Relaxed Fit', 'Oversized'];

for (let i = 13; i <= 50; i++) {
  const cat = CATEGORIES[i % CATEGORIES.length];
  const brand = BRANDS[i % BRANDS.length];
  const ret = RETAILERS[i % RETAILERS.length];
  const fit = FITS[i % FITS.length];
  const baseProduct = MOCK_PRODUCTS[(i - 1) % 12];

  MOCK_PRODUCTS.push({
    id: i,
    external_id: `GEN-CAT-${i.toString().padStart(3, '0')}`,
    retailer: ret,
    brand: brand,
    name: `${brand} Premium ${cat.endsWith('s') ? cat.slice(0, -1) : cat} Edition ${i}`,
    description: `High quality fashion item from ${brand} available on ${ret}. Ideal for smart casual styling.`,
    category: cat,
    subcategory: 'Casual',
    gender: i % 2 === 0 ? 'Unisex' : i % 3 === 0 ? 'Men' : 'Women',
    price: Math.floor((i * 180 + 499) % 4500 + 599),
    currency: 'INR',
    discount: Math.floor((i * 5) % 40),
    images: [baseProduct.images[0]],
    product_url: `https://www.${ret.toLowerCase().replace(/\s+/g, '')}.com/p/${i}`,
    affiliate_url: `https://${ret.toLowerCase().replace(/\s+/g, '')}.com/aff/aimirror/${i}`,
    available_sizes: cat === 'Jeans' ? ['30', '32', '34'] : cat === 'Shoes' ? ['UK 7', 'UK 8', 'UK 9'] : ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Navy', 'White', 'Beige'].slice(i % 4, (i % 4) + 1),
    fit_type: fit,
    material: '100% Premium Cotton',
    rating: Number((4.0 + (i % 10) * 0.1).toFixed(1)),
    size_charts: baseProduct.size_charts,
  });
}
